# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_remove_business_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
