# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
